version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

  app1:
    image: app
    container_name: app1
    #ports:
    #  - "8081:8080"
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/postgres
      spring.datasource.username: postgres
      spring.datasource.password: password

  app2:
    image: app
    container_name: app2
    #ports:
    #  - "8082:8080"
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/postgres
      spring.datasource.username: postgres
      spring.datasource.password: password

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'